CREATE TABLE `memorials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(120) NOT NULL,
	`name` varchar(120) NOT NULL,
	`role` varchar(80) NOT NULL,
	`birthDate` varchar(20) NOT NULL,
	`deathDate` varchar(20) NOT NULL,
	`church` varchar(160) NOT NULL DEFAULT '소망교회',
	`familyContact` varchar(120),
	`familyPhone` varchar(80),
	`verse` text,
	`verseRef` varchar(120),
	`summary` varchar(255) NOT NULL,
	`story` text NOT NULL,
	`servicePlace` varchar(255),
	`serviceTime` varchar(40),
	`visibility` enum('public','link','private') NOT NULL DEFAULT 'public',
	`status` enum('pending','published','private') NOT NULL DEFAULT 'pending',
	`timelineJson` text,
	`managerMemo` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `memorials_id` PRIMARY KEY(`id`),
	CONSTRAINT `memorials_slug_unique` UNIQUE(`slug`)
);
