export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  solapiApiKey: process.env.SOLAPI_API_KEY ?? "",
  solapiApiSecret: process.env.SOLAPI_API_SECRET ?? "",
  solapiFromNumber: process.env.SOLAPI_FROM_NUMBER ?? "",
  publicSiteUrl: process.env.PUBLIC_SITE_URL ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: Number(process.env.SMTP_PORT ?? "587"),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPassword: process.env.SMTP_PASSWORD ?? "",
  smtpFrom: process.env.SMTP_FROM ?? "",
  reminderDaysBefore: Number(process.env.REMINDER_DAYS_BEFORE ?? "1"),
  reminderSchedulerEnabled: process.env.REMINDER_SCHEDULER_ENABLED !== "false",
};
