export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // 카카오 알림톡 (알리고, 2026-09-23). 값은 서버 .env 에만 둔다.
  aligoApiKey: process.env.ALIGO_API_KEY ?? "",
  aligoUserId: process.env.ALIGO_USER_ID ?? "",
  aligoSenderKey: process.env.ALIGO_SENDER_KEY ?? "",
  aligoSender: process.env.ALIGO_SENDER ?? "",
  aligoTplReminderConfirm: process.env.ALIGO_TPL_REMINDER_CONFIRM ?? "",
  aligoTplReminderDayBefore: process.env.ALIGO_TPL_REMINDER_DAY_BEFORE ?? "",
  aligoTplVerifyCode: process.env.ALIGO_TPL_VERIFY_CODE ?? "",
  /** Y 이면 알리고가 실제로 보내지 않고 요청만 확인한다. */
  aligoTestMode: process.env.ALIGO_TEST_MODE === "Y",
  publicSiteUrl: process.env.PUBLIC_SITE_URL ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: Number(process.env.SMTP_PORT ?? "587"),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPassword: process.env.SMTP_PASSWORD ?? "",
  smtpFrom: process.env.SMTP_FROM ?? "",
  /** 키오스크 문의(전화번호)를 받을 업체 메일 주소. 비우면 DB 에만 남는다 (2026-09-16). */
  inquiryNotifyEmail: process.env.INQUIRY_NOTIFY_EMAIL ?? "",
  reminderDaysBefore: Number(process.env.REMINDER_DAYS_BEFORE ?? "1"),
  reminderSchedulerEnabled: process.env.REMINDER_SCHEDULER_ENABLED !== "false",
};
